services:
  orders-service:
    build:
      context: .
      dockerfile: Dockerfile.ord
    ports:
      - "8080:8080"
    container_name: orders-service
    volumes:
      - ./app:/app

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile.gat
    ports:
      - "8081:8081"
    container_name: gateway-service
    volumes:
      - ./app:/app

  users-service:
    build:
      context: .
      dockerfile: Dockerfile.use
    ports:
      - "8082:8082"
    container_name: users-service
    volumes:
      - ./app:/app

  events-service:
    build:
      context: .
      dockerfile: Dockerfile.eds
    ports:
      - "8083:8083"
    container_name: events-service
    volumes:
      - ./app:/app

  users-v2-service:
    build:
      context: .
      dockerfile: Dockerfile.usr
    ports:
      - "8084:8084"
    container_name: users-v2-service
    volumes:
      - ./app:/app

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15673:15672"
    container_name: rabbitmq