FROM python:3.11-slim

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8083

CMD ["uvicorn", "api.event_driven_system:app", "--host", "0.0.0.0", "--port", "8083"]
